import { InvestigatorSkillTypes } from "./InvestigatorSkills";

export enum InvestigatorStatTypes {
  education = 'education',
  strength = 'strength',
  dexterity = 'dexterity',
  intelligence = 'intelligence',
  constituition = 'constituition',
  appearance = 'appearance',
  power = 'power',
  size = 'size',
  sanity = 'sanity',
}

export interface InvestigatorOccupation {
  name: string
  description: string
  skillPoints: {
    type: InvestigatorStatTypes,
    multiplier: number,
  }[]
  creditRating: {
    min: number,
    max: number,
  }
  suggestedContacts: string[]
  skills: InvestigatorSkillTypes[]
  extraSkillTypes: number
  interpersonalSkills: number
  optionalSkillPoints?: {
    type: InvestigatorStatTypes,
    multiplier: number,
  }[]
}

// TODO separate types of pilot, driver, laborer, photographer
// TODO make two endpoints: one for fetching all occupation names and one for getting a specific occupation and move this to backend
export const occupationNames: string[] = [
  'Accountant',
  'Acrobat',
  'Actor (Film Star)',
  'Actor (Stage Actor)',
  'Agency Detective',
  'Alienist (Classic)',
  'Animal Trainer',
  'Antiquarian (Lovecraftian)',
  'Antique Dealer',
  'Archaeologist (Lovecraftian)',
  'Architect',
  'Artist',
  'Asylum Attendant',
  'Athlete',
  'Author (Lovecraftian)',
  'Bartender',
  'Big Game Hunter',
  'Book Dealer',
  'Bounty Hunter',
  'Boxer/Wrestler',
  'Butler',
  'Butler (Maid)',
  'Clergy, Member of the',
  'Cowboy/girl',
  'Craftsperson',
  'Criminal (Assassin)',
  'Criminal (Bank Robber)',
  'Criminal (Bootlegger)',
  'Criminal (Burglar)',
  'Criminal (Conman)',
  'Criminal (Gangster)',
  'Criminal (Fence)',
  'Criminal (Forger/Counterfeiter)',
  'Criminal (Gun Moll)',
  'Criminal (Smuggler)',
  'Criminal (Street Punk)',
  'Criminal (Thug)',
  'Cult Leader',
  'Designer',
  'Dilettante (Lovecraftian)',
  'Diver',
  'Drifter',
  'Driver',
  'Driver (Chauffeur)',
  'Driver (Taxi Driver)',
  'Editor',
  'Elected Official',
  'Engineer',
  'Entertainer',
  'Explorer (Classic)',
  'Farmer',
  'Federal Agent',
  'Firefighter',
  'Foreign Correspondent',
  'Forensic Surgeon',
  'Gambler',
  'Gentleman/lady',
  'Hobo',
  'Hospital Orderly',
  'Journalist (Investigative Journalist)',
  'Journalist (Reporter)',
  'Laboratory Assistant',
  'Laborer (Unskilled)',
  'Laborer (Lumberjack)',
  'Laborer (Miner)',
  'Lawyer',
  'Librarian (Lovecraftian)',
  'Mechanic',
  'Military Officer',
  'Missionary',
  'Mountain Climber',
  'Museum Curator',
  'Musician',
  'Nurse',
  'Occultist (Lovecraftian)',
  'Outdoors(wo)man',
  'Parapsychologist',
  'Pharmacist',
  'Photographer',
  'Photographer (Photojournalist)',
  'Pilot',
  'Police Detective/Officer (Lovecraftian)',
  'Private Investigator',
  'Professor (Lovecraftian)',
  'Prospector',
  'Prostitute',
  'Psychiatrist',
  'Psychologist',
  'Researcher',
  'Sailor',
  'Salesperson',
  'Scientist',
  'Secretary',
  'Shopkeeper',
  'Soldier/Marine',
  'Spy',
  'Student/Intern',
  'Stuntman',
  'Tribe Member',
  'Undertaker',
  'Union Activist',
  'Waitress/Waiter',
  'White-collar Worker',
  'Zealot',
  'Zookeeper',
]
