export const theme = {
  palette: {
    primary: 'blue',
    secondary: 'red',
  },
  typography: {
    h1: {
      fontFamily: 'Poppins',
      fontWeight: 400,
      fontSize: 34,
      lineHeight: '40px',
    },
    h2: {
      fontFamily: 'Poppins',
      fontWeight: 400,
      fontSize: 24,
      lineHeight: '32px',
      letterSpacing: 0.18,
    },
    h3: {
      fontFamily: 'Poppins',
      fontWeight: 700,
      fontSize: 18,
      lineHeight: '24px',
    },
    h4: {
      fontFamily: 'Poppins',
      fontWeight: 400,
      fontSize: 20,
      lineHeight: '28px',
      letterSpacing: 0.15,
    },
    h5: {
      fontFamily: 'Poppins',
      fontWeight: 700,
      fontSize: 16,
      lineHeight: '24px',
    },
    h6: {
      fontFamily: 'Poppins',
      fontWeight: 700,
      fontSize: 14,
      lineHeight: '20px',
    },
    subtitle1: {
      fontFamily: 'Barlow',
      fontWeight: 400,
      fontSize: 16,
      lineHeight: '24px',
      letterSpacing: 0.15,
    },
    subtitle2: {
      fontFamily: 'Barlow',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: '24px',
      letterSpacing: 0.1,
    },
    body1: {
      fontFamily: 'Barlow',
      fontWeight: 400,
      fontSize: 16,
      lineHeight: '24px',
      letterSpacing: 0.5,
    },
    body2: {
      fontFamily: 'Barlow',
      fontWeight: 400,
      fontSize: 14,
      lineHeight: '20px',
      letterSpacing: 0.25,
    },
    button: {
      fontFamily: 'Barlow',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: '16px',
      letterSpacing: 1.25,
    },
    caption: {
      fontFamily: 'Poppins',
      fontWeight: 400,
      fontSize: 12,
      lineHeight: '16px',
      letterSpacing: 0.4,
    },
    overline: {
      fontFamily: 'Poppins',
      fontWeight: 500,
      fontSize: 12,
      lineHeight: '16px',
      letterSpacing: 1.4,
    },
  },
}